server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: ${artifactId}
  profiles:
    # dev, test,删除app.env两边的@
    active: ${@app.env@:dev}
  main:
    allow-bean-definition-overriding: true